// Domain TLD pricing data — Tanzania Market (TZS)
export const TLD_PRICING: Record<string, { register: number; renew: number; transfer: number; popular?: boolean }> = {
  '.co.tz': { register: 35000, renew: 35000, transfer: 30000, popular: true },
  '.tz': { register: 25000, renew: 25000, transfer: 20000, popular: true },
  '.ac.tz': { register: 25000, renew: 25000, transfer: 20000, popular: false },
  '.or.tz': { register: 25000, renew: 25000, transfer: 20000, popular: false },
  '.go.tz': { register: 25000, renew: 25000, transfer: 20000, popular: false },
  '.com': { register: 30000, renew: 30000, transfer: 25000, popular: true },
  '.africa': { register: 22000, renew: 22000, transfer: 18000, popular: true },
  '.net': { register: 28000, renew: 28000, transfer: 24000 },
  '.org': { register: 26000, renew: 26000, transfer: 22000 },
  '.io': { register: 45000, renew: 45000, transfer: 38000 },
  '.info': { register: 20000, renew: 20000, transfer: 16000 },
  '.biz': { register: 22000, renew: 22000, transfer: 18000 },
  '.co': { register: 50000, renew: 50000, transfer: 42000 },
  '.me': { register: 25000, renew: 25000, transfer: 20000 },
  '.tech': { register: 35000, renew: 35000, transfer: 28000 },
  '.online': { register: 15000, renew: 15000, transfer: 12000 },
  '.site': { register: 15000, renew: 15000, transfer: 12000 },
  '.store': { register: 22000, renew: 22000, transfer: 18000 },
}

export const POPULAR_TLDS = Object.entries(TLD_PRICING)
  .filter(([, data]) => data.popular)
  .map(([tld, data]) => ({ tld, ...data }))

export const ALL_TLDS = Object.entries(TLD_PRICING).map(([tld, data]) => ({ tld, ...data }))

// Hosting packages — TZS pricing
export const HOSTING_PLANS = [
  {
    id: 'starter',
    name: 'Starter Hosting',
    type: 'shared',
    description: 'Kamili kwa tovuti za kibinafsi na blogu',
    price: 50000,
    period: 'year',
    popular: false,
    features: [
      '5 GB SSD Storage',
      '100 GB Bandwidth',
      'Tovuti 1',
      'SSL Bure',
      'Akaunti 3 za Barua Pepe',
      'Nakala ya Kila Siku',
      'cPanel Control Panel',
    ],
  },
  {
    id: 'business',
    name: 'Business Hosting',
    type: 'shared',
    description: 'Kamili kwa biashara zinazokua na duka la mtandaoni',
    price: 120000,
    period: 'year',
    popular: true,
    features: [
      '25 GB SSD Storage',
      'Bandwidth Isiyokuwa na Mwisho',
      'Tovuti 10',
      'SSL Bure',
      'Akaunti 25 za Barua Pepe',
      'Nakala ya Kila Siku',
      'cPanel Control Panel',
      'Jina la Tovuti Bure (.co.tz)',
      'Msaada wa Kipaumbele',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise Hosting',
    type: 'shared',
    description: 'Kwa tovuti zenye trafiki nyingi na programu nzito',
    price: 250000,
    period: 'year',
    popular: false,
    features: [
      '100 GB NVMe Storage',
      'Bandwidth Isiyokuwa na Mwisho',
      'Tovuti Isiyokuwa na Mwisho',
      'SSL (Wildcard) Bure',
      'Barua Pepe Isiyokuwa na Mwisho',
      'Nakala za Wakati Halisi',
      'cPanel + WHM',
      'Jina la Tovuti Bure (.com)',
      'IP Mahususi',
      'Msaada 24/7',
    ],
  },
  {
    id: 'vps-basic',
    name: 'VPS Basic',
    type: 'vps',
    description: 'Mlango kamili wa mzizi na rasilimali mahususi',
    price: 80000,
    period: 'month',
    popular: false,
    features: [
      '2 vCPU Cores',
      '4 GB RAM',
      '50 GB NVMe SSD',
      '2 TB Bandwidth',
      'Mlango kamili wa mzizi',
      '1 IPv4 Address',
      'Ubuntu / CentOS',
      'KVM Virtualization',
    ],
  },
  {
    id: 'vps-pro',
    name: 'VPS Pro',
    type: 'vps',
    description: 'VPS yenye nguvu kwa kazi nzito',
    price: 160000,
    period: 'month',
    popular: true,
    features: [
      '4 vCPU Cores',
      '8 GB RAM',
      '100 GB NVMe SSD',
      '4 TB Bandwidth',
      'Mlango kamili wa mzizi',
      '2 IPv4 Addresses',
      'Ubuntu / CentOS / Debian',
      'KVM Virtualization',
      'Managed Option',
    ],
  },
  {
    id: 'vps-ultra',
    name: 'VPS Ultra',
    type: 'vps',
    description: 'Utendaji wa juu zaidi kwa programu za kampuni',
    price: 320000,
    period: 'month',
    popular: false,
    features: [
      '8 vCPU Cores',
      '16 GB RAM',
      '200 GB NVMe SSD',
      '8 TB Bandwidth',
      'Mlango kamili wa mzizi',
      '3 IPv4 Addresses',
      'Linux Yoyote',
      'KVM Virtualization',
      'Fully Managed',
      'DDoS Protection',
    ],
  },
  {
    id: 'cloud-starter',
    name: 'Cloud Starter',
    type: 'cloud',
    description: 'Hosting ya wingu inayobadilika kwa urahisi',
    price: 200000,
    period: 'month',
    popular: false,
    features: [
      '2 vCPU Cores',
      '4 GB RAM',
      '80 GB SSD',
      '4 TB Transfer',
      'Auto-scaling',
      'Load Balancer',
      'Cloud Firewall',
      'Snapshots',
    ],
  },
  {
    id: 'cloud-business',
    name: 'Cloud Business',
    type: 'cloud',
    description: 'Miundombinu ya wingu yenye upatikanaji wa hali ya juu',
    price: 400000,
    period: 'month',
    popular: true,
    features: [
      '4 vCPU Cores',
      '8 GB RAM',
      '160 GB SSD',
      '8 TB Transfer',
      'Auto-scaling',
      'Load Balancer',
      'Cloud Firewall',
      'Snapshots + Backups',
      'CDN Integration',
      '99.99% SLA',
    ],
  },
]

// Email hosting plans
export const EMAIL_PLANS = [
  {
    id: 'email-starter',
    name: 'Barua Pepe ya Mwanzo',
    provider: 'custom',
    description: 'Barua pepe ya kitaalamu kwa watu binafsi na wafanyakazi huru',
    price: 25000,
    period: 'year',
    popular: false,
    features: [
      'Akaunti 1 ya Barua Pepe',
      '5 GB Storage',
      'Webmail Access',
      'Spam Protection',
      'IMAP/POP3/SMTP',
      'Mobile Sync',
    ],
  },
  {
    id: 'email-business',
    name: 'Barua Pepe ya Biashara',
    provider: 'custom',
    description: 'Barua pepe kamili kwa timu',
    price: 60000,
    period: 'year',
    popular: true,
    features: [
      'Akaunti 10 za Barua Pepe',
      '25 GB kwa kila Akaunti',
      'Webmail + Outlook',
      'Spam & Virus Protection',
      'IMAP/POP3/SMTP',
      'Mobile Sync',
      'Kalenda & Viambatisho',
      'Shared Mailbox',
    ],
  },
  {
    id: 'email-enterprise',
    name: 'Barua Pepe ya Kampuni',
    provider: 'custom',
    description: 'Barua pepe isiyokuwa na kikomo kwa mashirika makubwa',
    price: 120000,
    period: 'year',
    popular: false,
    features: [
      'Akaunti Isiyokuwa na Mwisho',
      '50 GB kwa kila Akaunti',
      'Webmail + Outlook',
      'Usalama wa Juu',
      'IMAP/POP3/SMTP',
      'Mobile Sync',
      'Kalenda & Viambatisho',
      'Shared Mailbox',
      'Distribution Lists',
      'Archiving',
    ],
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    provider: 'google',
    description: 'Seti ya barua pepe na ushirikiano ya Google',
    price: 150000,
    period: 'year',
    popular: false,
    features: [
      'Barua Pepe ya Desturi (@kampuni)',
      '30 GB Storage',
      'Gmail ya Biashara',
      'Google Drive',
      'Google Meet',
      'Google Calendar',
      'Google Docs/Sheets/Slides',
      'Google Chat',
      'Admin Console',
    ],
  },
  {
    id: 'zoho-workplace',
    name: 'Zoho Workplace',
    provider: 'zoho',
    description: 'Barua pepe ya biashara yenye bei nafuu na seti ya ofisi',
    price: 60000,
    period: 'year',
    popular: true,
    features: [
      'Barua Pepe ya Desturi (@kampuni)',
      '5 GB kwa kila Mtumiaji',
      'Zoho Mail Pro',
      'Zoho Drive (5 GB)',
      'Zoho Meeting',
      'Zoho Calendar',
      'Zoho Writer/Sheet/Show',
      'Zoho Cliq (Chat)',
      'Admin Panel',
    ],
  },
]

// SSL Certificate plans
export const SSL_PLANS = [
  {
    id: 'ssl-free',
    name: 'SSL Bure (Let\'s Encrypt)',
    type: 'free',
    description: 'SSL ya msingi kwa tovuti za kibinafsi na blogu',
    price: 0,
    period: 'year',
    popular: false,
    features: [
      'Uthibitishaji wa Jina la Tovuti',
      'Usimbaji fiche wa 256-bit',
      'Kusasisha kiotomatiki',
      'Uaminifu wa Kivinjari',
      'Jina la Tovuti Moja',
    ],
  },
  {
    id: 'ssl-positive',
    name: 'PositiveSSL',
    type: 'dv',
    description: 'SSL ya uthibitishaji haraka kwa biashara ndogo',
    price: 40000,
    period: 'year',
    popular: true,
    features: [
      'Uthibitishaji wa Jina la Tovuti',
      'Usimbaji fiche wa 256-bit',
      'Uaminifu wa Kivinjari 99.9%',
      'Jina la Tovuti Moja',
      'Toleo Bure',
      'Warranty ya $10,000',
      'Utoaji Haraka (dakika 15)',
    ],
  },
  {
    id: 'ssl-wildcard',
    name: 'SSL ya Wildcard',
    type: 'wildcard',
    description: 'Linda tovuti ndogo zisiyokuwa na kikomo kwa cheti moja',
    price: 180000,
    period: 'year',
    popular: false,
    features: [
      'Uthibitishaji wa Jina la Tovuti',
      'Usimbaji fiche wa 256-bit',
      'Uaminifu wa Kivinjari 99.9%',
      '*.tovuti.com',
      'Toleo Bure',
      'Warranty ya $50,000',
      'Tovuti Ndogo Isiyokuwa na Mwisho',
    ],
  },
  {
    id: 'ssl-ev',
    name: 'Cheti cha SSL cha EV',
    type: 'ev',
    description: 'Uthibitishaji Ulionyoshwa na bar ya kijani kwa uaminifu wa juu zaidi',
    price: 400000,
    period: 'year',
    popular: false,
    features: [
      'Uthibitishaji Ulionyoshwa',
      'Usimbaji fiche wa 256-bit',
      'Uaminifu wa Kivinjari 99.99%',
      'Jina la Tovuti Moja',
      'Toleo Bure',
      'Warranty ya $250,000',
      'Bar ya Kijani',
      'Uthibitishaji wa Biashara',
    ],
  },
  {
    id: 'ssl-multi',
    name: 'SSL ya Tovuti Nyingi',
    type: 'san',
    description: 'Linda hadi tovuti 5 kwa cheti moja',
    price: 280000,
    period: 'year',
    popular: false,
    features: [
      'Uthibitishaji wa Jina la Tovuti',
      'Usimbaji fiche wa 256-bit',
      'Uaminifu wa Kivinjari 99.9%',
      'Hadi Tovuti 5',
      'Toleo Bure',
      'Warranty ya $50,000',
      'SAN Support',
    ],
  },
]

// Bundle pricing — Tanzania Market
export const BUNDLE_PRICING = {
  'starter': {
    id: 'starter',
    name: 'Kifurushi cha Mwanzo',
    tagline: 'Jina + Barua Pepe',
    price: 55000,
    originalPrice: 70000,
    period: 'year',
    description: 'Kila unachohitaji kuanzisha barua pepe yako ya kitaalamu',
    features: [
      'Jina la tovuti (.co.tz)',
      'Akaunti 5 za barua pepe',
      '5GB kwa kila akaunti',
      'Webmail access',
      'Spam protection',
      'Cheti cha SSL bure',
    ],
    includes: ['Domain', 'Email', 'SSL'],
    color: 'emerald',
  },
  'business': {
    id: 'business',
    name: 'Kifurushi cha Biashara',
    tagline: 'Jina + Hosting + SSL',
    price: 130000,
    originalPrice: 170000,
    period: 'year',
    description: 'Uwepo kamili wa mtandaoni na hosting na usalama',
    features: [
      'Jina la tovuti (.co.tz)',
      'Hosting ya biashara (25GB SSD)',
      'Cheti cha SSL bure',
      'Akaunti 25 za barua pepe',
      'cPanel control panel',
      'Nakala za kila siku',
      'Kusasisha jina la tovuti bure',
    ],
    includes: ['Domain', 'Hosting', 'SSL', 'Email'],
    color: 'blue',
    popular: true,
  },
  'premium': {
    id: 'premium',
    name: 'Kifurushi cha Premium',
    tagline: 'Jina + Hosting + Barua + SSL',
    price: 200000,
    originalPrice: 300000,
    period: 'year',
    description: 'Seti kamili ya biashara yenye kila kitu',
    features: [
      'Jina la tovuti (.com)',
      'Hosting ya kampuni (100GB NVMe)',
      'Cheti cha SSL wildcard',
      'Barua pepe isiyokuwa na kikomo',
      'cPanel + WHM',
      'Nakala za wakati halisi',
      'IP mahususi',
      'Msaada 24/7 wa kipaumbele',
      'AI website builder',
    ],
    includes: ['Domain', 'Hosting', 'SSL', 'Email'],
    color: 'amber',
  },
}

// Premium domain suggestions — Tanzania
export const PREMIUM_DOMAINS = [
  { domain: 'dar.co.tz', category: 'Nchi', price: 500000 },
  { domain: 'biashara.tz', category: 'Biashara', price: 600000 },
  { domain: 'duka.co.tz', category: 'Biashara', price: 350000 },
  { domain: 'safari.tz', category: 'Usafiri', price: 450000 },
  { domain: 'chakula.co.tz', category: 'Chakula', price: 300000 },
  { domain: 'shule.tz', category: 'Elimu', price: 400000 },
  { domain: 'afya.co.tz', category: 'Afya', price: 550000 },
  { domain: 'fedha.tz', category: 'Fedha', price: 700000 },
  { domain: 'habari.co.tz', category: 'Habari', price: 380000 },
  { domain: 'michezo.tz', category: 'Michezo', price: 320000 },
]

// Swahili domain name suggestions
export const SWAHILI_SUGGESTIONS = [
  'biashara', 'duka', 'shule', 'hospitali', 'benki',
  'mkahawa', 'hotel', 'safari', 'geita', 'mwanza',
  'dodoma', 'arusha', 'zanzibar', 'mikoa', 'kilimo',
  'ujenzi', 'tech', 'digital', 'fundi', 'master',
]

// Analytics mock data for admin — Tanzania market
export const ANALYTICS_DATA = {
  totalRevenue: 85000000,
  monthlyRevenue: [
    { month: 'Jan', revenue: 5200000, domains: 85 },
    { month: 'Feb', revenue: 6100000, domains: 95 },
    { month: 'Mar', revenue: 5800000, domains: 90 },
    { month: 'Apr', revenue: 7200000, domains: 115 },
    { month: 'May', revenue: 7800000, domains: 125 },
    { month: 'Jun', revenue: 8500000, domains: 140 },
    { month: 'Jul', revenue: 9200000, domains: 152 },
    { month: 'Aug', revenue: 10100000, domains: 168 },
    { month: 'Sep', revenue: 9500000, domains: 155 },
    { month: 'Oct', revenue: 10800000, domains: 178 },
    { month: 'Nov', revenue: 11500000, domains: 190 },
    { month: 'Dec', revenue: 12300000, domains: 205 },
  ],
  revenueByService: [
    { name: 'Majina', value: 40, color: '#059669' },
    { name: 'Hosting', value: 30, color: '#0891b2' },
    { name: 'Barua Pepe', value: 14, color: '#d97706' },
    { name: 'SSL', value: 10, color: '#7c3aed' },
    { name: 'Vifurushi', value: 6, color: '#dc2626' },
  ],
  tldDistribution: [
    { tld: '.co.tz', count: 520, percentage: 32 },
    { tld: '.com', count: 380, percentage: 23 },
    { tld: '.tz', count: 250, percentage: 15 },
    { tld: '.ac.tz', count: 120, percentage: 7 },
    { tld: '.africa', count: 100, percentage: 6 },
    { tld: '.or.tz', count: 80, percentage: 5 },
    { tld: '.net', count: 70, percentage: 5 },
    { tld: '.Others', count: 110, percentage: 7 },
  ],
}

// Swahili translations
export const SWAHILI = {
  // Navigation
  home: 'Nyumbani',
  domains: 'Majina',
  search: 'Tafuta',
  hosting: 'Hosting',
  email: 'Barua Pepe',
  ssl: 'SSL',
  bundles: 'Vifurushi',
  dashboard: 'Dashibodi',
  premium: 'Premium',
  builder: 'KI Tengeneza Tovuti',
  settings: 'Mipangilio',

  // Hero
  heroBadge: 'Imeidhinishwa na TCRA',
  heroTitle: 'Uwepo Wako Mtandaoni',
  heroTitleHighlight: 'Unaanza Hapa',
  heroSubtitle: 'Tafuta, sajili, na simamia majina yako kwa urahisi. Lipa kupitia M-Pesa. tengeneza tovuti ya kuvutia kwa dakika.',
  heroSearchPlaceholder: 'Tafuta jina la tovuti...',
  heroSearchBtn: 'Tafuta',

  // Trust
  trustNoHidden: 'Hakuna ada zilizofichwa',
  trustInstant: 'Uanzishaji wa mara moja',
  trustSupport: 'Msaada 24/7 kupitia WhatsApp',
  trustMpesa: 'M-Pesa na Tigo Pesa',

  // Domain Search
  searchTitle: 'Tafuta Jina Kamili la Tovuti',
  searchSubtitle: 'Tafuta katika TLD 50+ na upate jina bora kwa biashara yako',
  searchPlaceholder: 'Ingiza jina (mfano: biashara)',
  available: 'Inapatikana',
  taken: 'Imeshachukuliwa',
  addToCart: 'Ongeza',
  inCart: 'Kwenye Gari',
  premiumTag: 'Premium',
  tanzaniaTlds: 'Tanzania',
  internationalTlds: 'Kimataifa',
  newTlds: 'TLD Mpya',
  popularSearches: 'Utafutaji Maarufu Tanzania',
  popularSearchesDesc: 'Majina maarufu yanayotafutwa nchini Tanzania',
  similarAvailable: 'Majina Yanayofanana',
  tryInstead: 'Jaribu badala yake',
  year: 'Mwaka',
  years: 'Miaka',
  save: 'Okoa',
  perYear: '/mwaka',
  total: 'Jumla',

  // Payment
  paymentSecure: 'Malipo Salama',
  paymentMethod: 'Njia ya Malipo',
  mpesa: 'M-Pesa',
  tigoPesa: 'Tigo Pesa',
  airtelMoney: 'Airtel Money',
  card: 'Kadi ya Benki',
  phonePlaceholder: '+255 6XX XXX XXX',
  payNow: 'Lipa Sasa',
  processing: 'Inasindikiza Malipo',
  enterPin: 'Tafadhali ingiza PIN yako kwenye simu',
  paymentSuccess: 'Malipo Yamefanikiwa!',
  paymentFailed: 'Malipo Yamecheleweshwa',
  cartEmpty: 'Gari lako ni tupu',
  cartEmptyDesc: 'Hakuna bidhaa kwenye gari lako',
  goSearch: 'Tafuta Majina',
  orderSummary: 'Muhtasari wa Oda',
  itemDomain: 'Jina',
  itemTld: 'TLD',
  itemYears: 'Miaka',
  itemPricePerYear: 'Bei/Mwaka',
  itemTotal: 'Jumla',
  removeItem: 'Ondoa',
  subtotal: 'Jumla ya Ndani',
  registrationFees: 'Ada ya Usajili',
  renewalFees: 'Ada ya Kusasisha',
  transferFees: 'Ada ya Uhamishaji',
  payingForYears: 'Unalipia kwa miaka',
  youSave: 'unaokoa',
  poweredBySelcom: 'Inatumwa na Selcom',
  mpesaTestimonial: 'Malipo ya M-Pesa zaidi ya 10,000 yamefanikiwa kwenye DomainHub',
  avgPaymentTime: 'Wastani wa muda wa malipo: sekunde 30',
  setUpDns: 'Weka DNS',
  downloadReceipt: 'Pakua Risiti',
  receiptSent: 'Risiti imetumwa kwenye barua pepe yako!',
  redirectingIn: 'Inaelekeza kwenye dashibodi kwa',
  seconds: 'sekunde',
  cancelRedirect: 'Sitisha',
  domainsPurchased: 'Majina Yanayonunuliwa',
  registrationDetails: 'Maelezo ya Usajili',
  paymentBreakdown: 'Mgawanyiko wa Malipo',

  // Dashboard
  myDomains: 'Majina Yangu',
  overview: 'Muhtasari',
  billing: 'Bili',
  active: 'Imefanya kazi',
  expired: 'Imeisha Muda',
  expiringSoon: 'Inaisha Karibun',
  renew: 'Sasisha',
  autoRenew: 'Kusasisha Kiotomatiki',
  autoRenewDesc: 'Jina litasasishwa moja kwa moja kabla ya kuisha',
  dnsManagement: 'Usimamizi wa DNS',
  contactPrivacy: 'Faragha ya Mawasiliano',
  contactPrivacyDesc: 'Ficha maelezo yako ya mawasiliano na wasio idhinishwa',
  expiryBannerCritical: 'majina yanayoisha ndani ya siku 30',
  expiryBannerWarning: 'majina yanayoisha ndani ya siku 90',
  criticalBadge: 'Kubwa',
  warningBadge: 'Onyo',
  soonBadge: 'Karibun',
  renewViaMpesa: 'Sasisha kwa M-Pesa',
  expiresLabel: 'Inaisha',
  daysLabel: 'siku',

  // Auth
  signIn: 'Ingia',
  signUp: 'Jisajili',
  email: 'Barua Pepe',
  password: 'Nenosiri',
  name: 'Jina',
  phone: 'Simu',
  forgotPassword: 'Umesahau nenosiri?',
  welcomeBack: 'Karibu Tena!',
  createAccount: 'Unda Akaunti',

  // Footer
  footerTagline: 'Jukwaa bora zaidi la usajili na usimamizi wa majina la tovuti nchini Tanzania. Rahisi, haraka, na bei nafuu.',
  footerDomains: 'Majina',
  footerServices: 'Huduma',
  footerSupport: 'Msaada',

  // FAQ
  faqTitle: 'Maswali Yanayoulizwa Mara Kwa Mara',
  faq1Q: 'Jina la tovuti ni nini?',
  faq1A: 'Jina la tovuti (domain name) ni anwani ya wavuti yako mtandaoni, kama vile biashara.co.tz. Hii ndio njia watu wanavyotumia kupata tovuti yako.',
  faq2Q: '.co.tz ni nini?',
  faq2A: '.co.tz ni nyanja ya juu ya Tanzania kwa makampuni na biashara. Inaonyesha kuwa biashara yako iko nchini Tanzania na hutoa uaminifu kwa wateja.',
  faq3Q: 'Ninawezaje lipa kwa M-Pesa?',
  faq3A: 'Chagua M-Pesa kama njia ya malipo, ingiza nambari yako ya simu, na utapokea ujumbe wa STK push. Ingiza PIN yako ku kukamilisha malipo. Ni rahisi na salama!',
  faq4Q: 'Je, nitapokea cheti cha SSL bure?',
  faq4A: 'Ndiyo! Kila jina la tovuti linalosajiliwa kupitia DomainHub linakuja na cheti cha SSL bure kutoka Let\'s Encrypt ili kulinda wavuti yako.',
}

export const ENGLISH = {
  // Navigation
  home: 'Home',
  domains: 'Domains',
  search: 'Search',
  hosting: 'Hosting',
  email: 'Email',
  ssl: 'SSL',
  bundles: 'Bundles',
  dashboard: 'Dashboard',
  premium: 'Premium',
  builder: 'AI Website Builder',
  settings: 'Settings',

  // Hero
  heroBadge: 'TCRA Accredited',
  heroTitle: 'Your Online Presence',
  heroTitleHighlight: 'Starts Here',
  heroSubtitle: 'Search, register, and manage your domains with ease. Pay via M-Pesa. Build a stunning website in minutes.',
  heroSearchPlaceholder: 'Find your perfect domain name...',
  heroSearchBtn: 'Search',

  // Trust
  trustNoHidden: 'No hidden fees',
  trustInstant: 'Instant activation',
  trustSupport: '24/7 support via WhatsApp',
  trustMpesa: 'M-Pesa & Tigo Pesa',

  // Domain Search
  searchTitle: 'Find Your Perfect Domain',
  searchSubtitle: 'Search across 50+ TLDs and find the perfect name for your business',
  searchPlaceholder: 'Enter a name (e.g., biashara)',
  available: 'Available',
  taken: 'Taken',
  addToCart: 'Add',
  inCart: 'In Cart',
  premiumTag: 'Premium',
  tanzaniaTlds: 'Tanzania',
  internationalTlds: 'International',
  newTlds: 'New TLDs',
  popularSearches: 'Popular Tanzania Searches',
  popularSearchesDesc: 'Trending domain searches in Tanzania',
  similarAvailable: 'Similar Domains',
  tryInstead: 'Try these instead',
  year: 'Year',
  years: 'Years',
  save: 'Save',
  perYear: '/yr',
  total: 'Total',

  // Payment
  paymentSecure: 'Secure Checkout',
  paymentMethod: 'Payment Method',
  mpesa: 'M-Pesa',
  tigoPesa: 'Tigo Pesa',
  airtelMoney: 'Airtel Money',
  card: 'Bank Card',
  phonePlaceholder: '+255 6XX XXX XXX',
  payNow: 'Pay Now',
  processing: 'Processing Payment',
  enterPin: 'Please enter your PIN on your phone',
  paymentSuccess: 'Payment Successful!',
  paymentFailed: 'Payment Timed Out',
  cartEmpty: 'Your cart is empty',
  cartEmptyDesc: 'No items in your cart',
  goSearch: 'Search Domains',
  orderSummary: 'Order Summary',
  itemDomain: 'Domain',
  itemTld: 'TLD',
  itemYears: 'Years',
  itemPricePerYear: 'Price/Yr',
  itemTotal: 'Total',
  removeItem: 'Remove',
  subtotal: 'Subtotal',
  registrationFees: 'Registration Fees',
  renewalFees: 'Renewal Fees',
  transferFees: 'Transfer Fees',
  payingForYears: 'Paying for',
  youSave: 'save',
  poweredBySelcom: 'Powered by Selcom',
  mpesaTestimonial: 'Over 10,000 successful M-Pesa payments on DomainHub',
  avgPaymentTime: 'Average payment time: 30 seconds',
  setUpDns: 'Set up DNS',
  downloadReceipt: 'Download Receipt',
  receiptSent: 'Receipt sent to your email!',
  redirectingIn: 'Redirecting to dashboard in',
  seconds: 'seconds',
  cancelRedirect: 'Cancel',
  domainsPurchased: 'Domains Purchased',
  registrationDetails: 'Registration Details',
  paymentBreakdown: 'Payment Breakdown',

  // Dashboard
  myDomains: 'My Domains',
  overview: 'Overview',
  billing: 'Billing',
  active: 'Active',
  expired: 'Expired',
  expiringSoon: 'Expiring Soon',
  renew: 'Renew',
  autoRenew: 'Auto-Renew',
  autoRenewDesc: 'Domain will be automatically renewed before expiry',
  dnsManagement: 'DNS Management',
  contactPrivacy: 'Contact Privacy',
  contactPrivacyDesc: 'Hide your personal contact details from the public',
  expiryBannerCritical: 'domains expiring within 30 days',
  expiryBannerWarning: 'domains expiring within 90 days',
  criticalBadge: 'Critical',
  warningBadge: 'Warning',
  soonBadge: 'Soon',
  renewViaMpesa: 'Renew via M-Pesa',
  expiresLabel: 'Expires',
  daysLabel: 'days',

  // Auth
  signIn: 'Sign In',
  signUp: 'Sign Up',
  email: 'Email',
  password: 'Password',
  name: 'Name',
  phone: 'Phone',
  forgotPassword: 'Forgot password?',
  welcomeBack: 'Welcome Back!',
  createAccount: 'Create Account',

  // Footer
  footerTagline: "Tanzania's premier domain registration and management platform. Simple, fast, and affordable.",
  footerDomains: 'Domains',
  footerServices: 'Services',
  footerSupport: 'Support',

  // FAQ
  faqTitle: 'Frequently Asked Questions',
  faq1Q: 'What is a domain name?',
  faq1A: 'A domain name is your website address online, like biashara.co.tz. It\'s how people find your website.',
  faq2Q: 'What is .co.tz?',
  faq2A: '.co.tz is Tanzania\'s top-level domain for companies and businesses. It shows your business is in Tanzania and builds trust.',
  faq3Q: 'How do I pay with M-Pesa?',
  faq3A: 'Choose M-Pesa as payment method, enter your phone number, and you\'ll receive an STK push. Enter your PIN to complete. Easy and secure!',
  faq4Q: 'Do I get a free SSL certificate?',
  faq4A: 'Yes! Every domain registered through DomainHub comes with a free SSL certificate from Let\'s Encrypt.',
}

// Default currency is TZS
export const CURRENCY_CODE = 'TZS'

export function formatCurrency(amount: number, currency: string = CURRENCY_CODE): string {
  if (currency === 'TZS') {
    return `TZS ${new Intl.NumberFormat('en-TZ').format(amount)}`
  }
  return new Intl.NumberFormat('en-TZ', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function getDaysUntilExpiry(expiresAt: string): number {
  const now = new Date()
  const expiry = new Date(expiresAt)
  const diff = expiry.getTime() - now.getTime()
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}

// Traffic-light expiry status
export function getExpiryStatus(days: number): { label: string; color: string; indicator: 'green' | 'yellow' | 'red' } {
  if (days <= 0) return { label: 'Imeisha', color: 'text-red-600 bg-red-50', indicator: 'red' }
  if (days <= 30) return { label: `${days} siku`, color: 'text-amber-600 bg-amber-50', indicator: 'yellow' }
  if (days <= 90) return { label: `${days} siku`, color: 'text-yellow-600 bg-yellow-50', indicator: 'yellow' }
  return { label: `${days} siku`, color: 'text-green-600 bg-green-50', indicator: 'green' }
}
